### PR TITLE
[Arabic (العربية)] translation

### PR DESCRIPTION
**Pull request by djennadhamza**
Hi every one,
opened issue #1687
I started to translate nuxtjs.org to arabic language,
please feel free to evaluate my translation or improve it

https://github.com/djennadhamza/nuxtjs.org

i finished the configuration files

i18n configuration

 18n file
 i18n block on nuxt.config

i still not finished the other files.

### CODE REVIEW

**Comment by djennadhamza** [comment]
Hi @smarroufin , sorry for the inconvenience. I've updated the branch to main.
i'm still learning how to contribute.

**Comment by KareemDa** [comment]
Hello, If  I want to start translating the website, should I start in this branch or it's overridden?

**Comment by clemcode** [comment]
Hi @KareemDa 
As far as I can see this branch is stale, I would advise to start from a fresh branch. As @smarroufin said, your PR should only contain a new folder in `content/${lang}` and a file in `i18n/${lang}.js`.

The next step for us is to determine a translation lead for the Arabic lang as it is not the case for now. Take a look at this discussion if you want to be involved:
[https://github.com/nuxt/translations/discussions/3](https://github.com/nuxt/translations/discussions/3)

Thank you for the proposal!

**Comment by KareemDa** [comment]
Thank you @clemcode for your reply.
I've tried to go to the link but it gives me 404

**Comment by clemcode** [comment]
Hi @KareemDa 

We couldn't add you to the repository, I contacted the Github support and they ask you to reach out to them directly.

Could you open a ticket here? https://support.github.com/ mentioning the repo we're trying to add you to? (https://github.com/nuxt/translations)

Sorry for the inconvenience, hope you can resolve it with the Github support.

**Comment by djennadhamza** [comment]
i fixed some errors i'll continue the translations, @KareemDa If you want to cooperate, i'm ready.

**Pull request closed without merging**
